"""user 添加 is_superuser, phone 改为 nullable

Revision ID: 056e63e9318f
Revises: 44d7d263e34a
Create Date: 2026-04-07 14:58:03.193865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '056e63e9318f'
down_revision: Union[str, Sequence[str], None] = '44d7d263e34a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_superuser', sa.Boolean(), nullable=False))
    op.alter_column('user', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('user', 'is_superuser')
    # ### end Alembic commands ###
