"""add article slug excerpt is_pinned view_count and category description

Revision ID: 1036c2a0a34b
Revises: a3b8f1c2d4e5
Create Date: 2026-04-09 08:36:50.127075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1036c2a0a34b'
down_revision: Union[str, Sequence[str], None] = 'a3b8f1c2d4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('slug', sa.String(length=200), nullable=False))
    op.add_column('article', sa.Column('excerpt', sa.String(length=500), nullable=False))
    op.add_column('article', sa.Column('is_pinned', sa.Boolean(), nullable=False))
    op.add_column('article', sa.Column('view_count', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_article_slug'), 'article', ['slug'], unique=True)
    op.drop_column('article', 'summary')
    op.add_column('category', sa.Column('description', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'description')
    op.add_column('article', sa.Column('summary', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_article_slug'), table_name='article')
    op.drop_column('article', 'view_count')
    op.drop_column('article', 'is_pinned')
    op.drop_column('article', 'excerpt')
    op.drop_column('article', 'slug')
    # ### end Alembic commands ###
