"""user group_id FK, drop user_group table

Revision ID: 52f161db130f
Revises: d38a2d8ff71f
Create Date: 2026-04-09 12:07:27.925792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52f161db130f'
down_revision: Union[str, Sequence[str], None] = 'd38a2d8ff71f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. 先加 group_id 列
    op.add_column('user', sa.Column('group_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_user_group_id'), 'user', ['group_id'], unique=False)
    op.create_foreign_key('fk_user_group_id', 'user', 'permission_group', ['group_id'], ['id'], ondelete='SET NULL')

    # 2. 从 user_group 迁移数据（取每个用户的第一个组）
    op.execute("""
        UPDATE "user" SET group_id = sub.group_id
        FROM (
            SELECT DISTINCT ON (user_id) user_id, group_id
            FROM user_group
            ORDER BY user_id
        ) sub
        WHERE "user".id = sub.user_id
    """)

    # 3. 删除旧关联表
    op.drop_table('user_group')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_index(op.f('ix_user_group_id'), table_name='user')
    op.drop_column('user', 'group_id')
    op.create_table('user_group',
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['permission_group.id'], name=op.f('user_group_group_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('user_group_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'group_id', name=op.f('user_group_pkey'))
    )
    # ### end Alembic commands ###
