services:
  api:
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build:
      dockerfile: Dockerfile.dev
    deploy:
      resources:
        limits:
          memory: 1G
    volumes:
      - ./frontend:/app
      - next_cache:/app/.next

  gateway:
    entrypoint: ["sh", "/usr/local/openresty/nginx/dev-entrypoint.sh"]
    environment:
      - RATE_LIMIT_MULTIPLIER=10
    volumes:
      - ./gateway/lua:/usr/local/openresty/nginx/lua
      - ./gateway/conf.d:/etc/nginx/conf.d
      - ./gateway/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./gateway/dev-entrypoint.sh:/usr/local/openresty/nginx/dev-entrypoint.sh

  db:
    ports:
      - "15432:5432"

volumes:
  next_cache:

