services:
  api:
    volumes:
      - ./backend:/app

  frontend:
    build:
      dockerfile: ../docker/frontend.dev.Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next

  db:
    ports:
      - "15432:5432"
