services:
  gateway:
    image: ghcr.io/whw23/mudasky-gateway:dev
    build:
      context: ./gateway
      dockerfile: Dockerfile
    entrypoint: ["sh", "/usr/local/openresty/nginx/dev-entrypoint.sh"]
    ports:
      - "80:80"
    environment:
      - RATE_LIMIT_MULTIPLIER=10
    volumes:
      - ./gateway/lua:/usr/local/openresty/nginx/lua
      - ./gateway/conf.d:/etc/nginx/conf.d
      - ./gateway/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./gateway/dev-entrypoint.sh:/usr/local/openresty/nginx/dev-entrypoint.sh

  frontend:
    image: ghcr.io/whw23/mudasky-frontend:dev
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    deploy:
      resources:
        limits:
          memory: 2G
    volumes:
      - ./frontend:/app
      - next_cache:/app/.next

  api:
    image: ghcr.io/whw23/mudasky-api:dev
    build:
      context: ./backend
      dockerfile: api/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEBUG=true
    volumes:
      - ./backend:/app

  db:
    image: ghcr.io/whw23/mudasky-db:dev
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "15432:5432"

volumes:
  next_cache:
