"""add program admission requirements

Revision ID: 5b2340b33e91
Revises: 446e97e3ccbe
Create Date: 2026-05-14 06:42:08.848598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b2340b33e91'
down_revision: Union[str, Sequence[str], None] = '446e97e3ccbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('university_program', sa.Column('admission_requirements', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('university_program', 'admission_requirements')
    # ### end Alembic commands ###
