"""article file_url to file_id and content_type default html

Revision ID: 90ae0c481136
Revises: a2e5e4581990
Create Date: 2026-04-20 13:54:02.956884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90ae0c481136'
down_revision: Union[str, Sequence[str], None] = 'a2e5e4581990'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('file_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'article', 'image', ['file_id'], ['id'])
    op.drop_column('article', 'file_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('file_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.drop_column('article', 'file_id')
    # ### end Alembic commands ###
