"""extend success_case with university and image fields

Revision ID: a2e5e4581990
Revises: b5e792a3ca33
Create Date: 2026-04-20 12:08:46.136744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2e5e4581990'
down_revision: Union[str, Sequence[str], None] = 'b5e792a3ca33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('success_case', sa.Column('university_id', sa.String(length=36), nullable=True))
    op.add_column('success_case', sa.Column('avatar_image_id', sa.String(length=36), nullable=True))
    op.add_column('success_case', sa.Column('offer_image_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'success_case', 'image', ['avatar_image_id'], ['id'])
    op.create_foreign_key(None, 'success_case', 'image', ['offer_image_id'], ['id'])
    op.create_foreign_key(None, 'success_case', 'university', ['university_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'success_case', type_='foreignkey')
    op.drop_constraint(None, 'success_case', type_='foreignkey')
    op.drop_constraint(None, 'success_case', type_='foreignkey')
    op.drop_column('success_case', 'offer_image_id')
    op.drop_column('success_case', 'avatar_image_id')
    op.drop_column('success_case', 'university_id')
    # ### end Alembic commands ###
