"""extend university table and add university_image

Revision ID: b5e792a3ca33
Revises: d6852e5dd8e4
Create Date: 2026-04-20 11:50:43.300880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b5e792a3ca33'
down_revision: Union[str, Sequence[str], None] = 'd6852e5dd8e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('university_image',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('university_id', sa.String(length=36), nullable=False),
    sa.Column('image_id', sa.String(length=36), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ),
    sa.ForeignKeyConstraint(['university_id'], ['university.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('university', sa.Column('logo_image_id', sa.String(length=36), nullable=True))
    op.add_column('university', sa.Column('admission_requirements', sa.Text(), nullable=True))
    op.add_column('university', sa.Column('scholarship_info', sa.Text(), nullable=True))
    op.add_column('university', sa.Column('qs_rankings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('university', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('university', sa.Column('longitude', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'university', 'image', ['logo_image_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'university', type_='foreignkey')
    op.drop_column('university', 'longitude')
    op.drop_column('university', 'latitude')
    op.drop_column('university', 'qs_rankings')
    op.drop_column('university', 'scholarship_info')
    op.drop_column('university', 'admission_requirements')
    op.drop_column('university', 'logo_image_id')
    op.drop_table('university_image')
    # ### end Alembic commands ###
