"""给 GeoJSON 文件添加多语言 name 字段。

运行：python3 scripts/translate-geo.py
输出：直接覆盖 frontend/public/geo/ 下的 5 个 JSON 文件。
"""

import json
import os

GEO_DIR = os.path.join(os.path.dirname(__file__), "..", "frontend", "public", "geo")

# fmt: off

WORLD_NAMES = {
    "索马里": {"en": "Somalia", "ja": "ソマリア", "de": "Somalia"},
    "列支敦士登公国": {"en": "Liechtenstein", "ja": "リヒテンシュタイン", "de": "Liechtenstein"},
    "摩洛哥": {"en": "Morocco", "ja": "モロッコ", "de": "Marokko"},
    "西撒哈拉": {"en": "Western Sahara", "ja": "西サハラ", "de": "Westsahara"},
    "塞尔维亚共和国": {"en": "Serbia", "ja": "セルビア", "de": "Serbien"},
    "阿富汗": {"en": "Afghanistan", "ja": "アフガニスタン", "de": "Afghanistan"},
    "安哥拉": {"en": "Angola", "ja": "アンゴラ", "de": "Angola"},
    "阿尔巴尼亚": {"en": "Albania", "ja": "アルバニア", "de": "Albanien"},
    "Aland": {"en": "Åland Islands", "ja": "オーランド諸島", "de": "Åland"},
    "安道尔公国": {"en": "Andorra", "ja": "アンドラ", "de": "Andorra"},
    "阿联酋": {"en": "UAE", "ja": "アラブ首長国連邦", "de": "VAE"},
    "阿根廷": {"en": "Argentina", "ja": "アルゼンチン", "de": "Argentinien"},
    "亚美尼亚": {"en": "Armenia", "ja": "アルメニア", "de": "Armenien"},
    "美属萨摩亚群岛": {"en": "American Samoa", "ja": "米領サモア", "de": "Amerikanisch-Samoa"},
    "法属南半球和南极领地": {"en": "French Southern Territories", "ja": "フランス領南方・南極地域", "de": "Französische Süd- und Antarktisgebiete"},
    "安提瓜和巴布达": {"en": "Antigua and Barbuda", "ja": "アンティグア・バーブーダ", "de": "Antigua und Barbuda"},
    "澳大利亚": {"en": "Australia", "ja": "オーストラリア", "de": "Australien"},
    "奥地利": {"en": "Austria", "ja": "オーストリア", "de": "Österreich"},
    "阿塞拜疆": {"en": "Azerbaijan", "ja": "アゼルバイジャン", "de": "Aserbaidschan"},
    "布隆迪": {"en": "Burundi", "ja": "ブルンジ", "de": "Burundi"},
    "比利时": {"en": "Belgium", "ja": "ベルギー", "de": "Belgien"},
    "贝宁": {"en": "Benin", "ja": "ベナン", "de": "Benin"},
    "布基纳法索": {"en": "Burkina Faso", "ja": "ブルキナファソ", "de": "Burkina Faso"},
    "孟加拉国": {"en": "Bangladesh", "ja": "バングラデシュ", "de": "Bangladesch"},
    "保加利亚": {"en": "Bulgaria", "ja": "ブルガリア", "de": "Bulgarien"},
    "巴林": {"en": "Bahrain", "ja": "バーレーン", "de": "Bahrain"},
    "巴哈马": {"en": "Bahamas", "ja": "バハマ", "de": "Bahamas"},
    "波斯尼亚和黑塞哥维那": {"en": "Bosnia and Herzegovina", "ja": "ボスニア・ヘルツェゴビナ", "de": "Bosnien und Herzegowina"},
    "白俄罗斯": {"en": "Belarus", "ja": "ベラルーシ", "de": "Belarus"},
    "伯利兹": {"en": "Belize", "ja": "ベリーズ", "de": "Belize"},
    "百慕大": {"en": "Bermuda", "ja": "バミューダ", "de": "Bermuda"},
    "玻利维亚": {"en": "Bolivia", "ja": "ボリビア", "de": "Bolivien"},
    "巴西": {"en": "Brazil", "ja": "ブラジル", "de": "Brasilien"},
    "巴巴多斯": {"en": "Barbados", "ja": "バルバドス", "de": "Barbados"},
    "文莱": {"en": "Brunei", "ja": "ブルネイ", "de": "Brunei"},
    "不丹": {"en": "Bhutan", "ja": "ブータン", "de": "Bhutan"},
    "博茨瓦纳": {"en": "Botswana", "ja": "ボツワナ", "de": "Botswana"},
    "中非共和国": {"en": "Central African Republic", "ja": "中央アフリカ共和国", "de": "Zentralafrikanische Republik"},
    "加拿大": {"en": "Canada", "ja": "カナダ", "de": "Kanada"},
    "瑞士": {"en": "Switzerland", "ja": "スイス", "de": "Schweiz"},
    "智利": {"en": "Chile", "ja": "チリ", "de": "Chile"},
    "中国": {"en": "China", "ja": "中国", "de": "China"},
    "科特迪瓦": {"en": "Côte d'Ivoire", "ja": "コートジボワール", "de": "Elfenbeinküste"},
    "喀麦隆": {"en": "Cameroon", "ja": "カメルーン", "de": "Kamerun"},
    "刚果(金)": {"en": "DR Congo", "ja": "コンゴ民主共和国", "de": "Demokratische Republik Kongo"},
    "刚果(布)": {"en": "Republic of the Congo", "ja": "コンゴ共和国", "de": "Republik Kongo"},
    "哥伦比亚": {"en": "Colombia", "ja": "コロンビア", "de": "Kolumbien"},
    "科摩罗": {"en": "Comoros", "ja": "コモロ", "de": "Komoren"},
    "佛得角": {"en": "Cape Verde", "ja": "カーボベルデ", "de": "Kap Verde"},
    "哥斯达黎加": {"en": "Costa Rica", "ja": "コスタリカ", "de": "Costa Rica"},
    "古巴": {"en": "Cuba", "ja": "キューバ", "de": "Kuba"},
    "库拉索岛": {"en": "Curaçao", "ja": "キュラソー", "de": "Curaçao"},
    "开曼群岛": {"en": "Cayman Islands", "ja": "ケイマン諸島", "de": "Kaimaninseln"},
    "北塞浦路斯": {"en": "Northern Cyprus", "ja": "北キプロス", "de": "Nordzypern"},
    "塞浦路斯": {"en": "Cyprus", "ja": "キプロス", "de": "Zypern"},
    "捷克共和国": {"en": "Czech Republic", "ja": "チェコ", "de": "Tschechien"},
    "德国": {"en": "Germany", "ja": "ドイツ", "de": "Deutschland"},
    "吉布提": {"en": "Djibouti", "ja": "ジブチ", "de": "Dschibuti"},
    "多米尼克": {"en": "Dominica", "ja": "ドミニカ国", "de": "Dominica"},
    "丹麦": {"en": "Denmark", "ja": "デンマーク", "de": "Dänemark"},
    "多明尼加共和国": {"en": "Dominican Republic", "ja": "ドミニカ共和国", "de": "Dominikanische Republik"},
    "阿尔及利亚": {"en": "Algeria", "ja": "アルジェリア", "de": "Algerien"},
    "厄瓜多尔": {"en": "Ecuador", "ja": "エクアドル", "de": "Ecuador"},
    "埃及": {"en": "Egypt", "ja": "エジプト", "de": "Ägypten"},
    "厄立特里亚": {"en": "Eritrea", "ja": "エリトリア", "de": "Eritrea"},
    "西班牙": {"en": "Spain", "ja": "スペイン", "de": "Spanien"},
    "爱沙尼亚": {"en": "Estonia", "ja": "エストニア", "de": "Estland"},
    "埃塞俄比亚": {"en": "Ethiopia", "ja": "エチオピア", "de": "Äthiopien"},
    "芬兰": {"en": "Finland", "ja": "フィンランド", "de": "Finnland"},
    "斐": {"en": "Fiji", "ja": "フィジー", "de": "Fidschi"},
    "福克兰群岛": {"en": "Falkland Islands", "ja": "フォークランド諸島", "de": "Falklandinseln"},
    "法国": {"en": "France", "ja": "フランス", "de": "Frankreich"},
    "法罗群岛": {"en": "Faroe Islands", "ja": "フェロー諸島", "de": "Färöer"},
    "密克罗尼西亚": {"en": "Micronesia", "ja": "ミクロネシア", "de": "Mikronesien"},
    "加蓬": {"en": "Gabon", "ja": "ガボン", "de": "Gabun"},
    "英国": {"en": "United Kingdom", "ja": "イギリス", "de": "Vereinigtes Königreich"},
    "格鲁吉亚": {"en": "Georgia", "ja": "ジョージア", "de": "Georgien"},
    "加纳": {"en": "Ghana", "ja": "ガーナ", "de": "Ghana"},
    "几内亚": {"en": "Guinea", "ja": "ギニア", "de": "Guinea"},
    "冈比亚": {"en": "Gambia", "ja": "ガンビア", "de": "Gambia"},
    "几内亚比绍": {"en": "Guinea-Bissau", "ja": "ギニアビサウ", "de": "Guinea-Bissau"},
    "赤道几内亚": {"en": "Equatorial Guinea", "ja": "赤道ギニア", "de": "Äquatorialguinea"},
    "希腊": {"en": "Greece", "ja": "ギリシャ", "de": "Griechenland"},
    "格林纳达": {"en": "Grenada", "ja": "グレナダ", "de": "Grenada"},
    "格陵兰": {"en": "Greenland", "ja": "グリーンランド", "de": "Grönland"},
    "危地马拉": {"en": "Guatemala", "ja": "グアテマラ", "de": "Guatemala"},
    "关岛": {"en": "Guam", "ja": "グアム", "de": "Guam"},
    "圭亚那": {"en": "Guyana", "ja": "ガイアナ", "de": "Guyana"},
    "赫德岛和麦克唐纳群岛": {"en": "Heard Island", "ja": "ハード島", "de": "Heard und McDonaldinseln"},
    "洪都拉斯": {"en": "Honduras", "ja": "ホンジュラス", "de": "Honduras"},
    "克罗地亚": {"en": "Croatia", "ja": "クロアチア", "de": "Kroatien"},
    "海地": {"en": "Haiti", "ja": "ハイチ", "de": "Haiti"},
    "匈牙利": {"en": "Hungary", "ja": "ハンガリー", "de": "Ungarn"},
    "印度尼西亚": {"en": "Indonesia", "ja": "インドネシア", "de": "Indonesien"},
    "马恩岛": {"en": "Isle of Man", "ja": "マン島", "de": "Isle of Man"},
    "印度": {"en": "India", "ja": "インド", "de": "Indien"},
    "Br. Indian Ocean Ter.": {"en": "British Indian Ocean Territory", "ja": "イギリス領インド洋地域", "de": "Britisches Territorium im Indischen Ozean"},
    "爱尔兰": {"en": "Ireland", "ja": "アイルランド", "de": "Irland"},
    "伊朗": {"en": "Iran", "ja": "イラン", "de": "Iran"},
    "伊拉克": {"en": "Iraq", "ja": "イラク", "de": "Irak"},
    "冰岛": {"en": "Iceland", "ja": "アイスランド", "de": "Island"},
    "以色列": {"en": "Israel", "ja": "イスラエル", "de": "Israel"},
    "意大利": {"en": "Italy", "ja": "イタリア", "de": "Italien"},
    "牙买加": {"en": "Jamaica", "ja": "ジャマイカ", "de": "Jamaika"},
    "泽西岛": {"en": "Jersey", "ja": "ジャージー", "de": "Jersey"},
    "约旦": {"en": "Jordan", "ja": "ヨルダン", "de": "Jordanien"},
    "日本": {"en": "Japan", "ja": "日本", "de": "Japan"},
    "锡亚琴冰川": {"en": "Siachen Glacier", "ja": "シアチェン氷河", "de": "Siachen-Gletscher"},
    "哈萨克斯坦": {"en": "Kazakhstan", "ja": "カザフスタン", "de": "Kasachstan"},
    "肯尼亚": {"en": "Kenya", "ja": "ケニア", "de": "Kenia"},
    "吉尔吉斯斯坦": {"en": "Kyrgyzstan", "ja": "キルギス", "de": "Kirgisistan"},
    "柬埔寨": {"en": "Cambodia", "ja": "カンボジア", "de": "Kambodscha"},
    "基里巴斯": {"en": "Kiribati", "ja": "キリバス", "de": "Kiribati"},
    "韩国": {"en": "South Korea", "ja": "韓国", "de": "Südkorea"},
    "科威特": {"en": "Kuwait", "ja": "クウェート", "de": "Kuwait"},
    "老挝": {"en": "Laos", "ja": "ラオス", "de": "Laos"},
    "黎巴嫩": {"en": "Lebanon", "ja": "レバノン", "de": "Libanon"},
    "利比里亚": {"en": "Liberia", "ja": "リベリア", "de": "Liberia"},
    "利比亚": {"en": "Libya", "ja": "リビア", "de": "Libyen"},
    "圣卢西亚岛": {"en": "Saint Lucia", "ja": "セントルシア", "de": "St. Lucia"},
    "斯里兰卡": {"en": "Sri Lanka", "ja": "スリランカ", "de": "Sri Lanka"},
    "莱索托": {"en": "Lesotho", "ja": "レソト", "de": "Lesotho"},
    "立陶宛": {"en": "Lithuania", "ja": "リトアニア", "de": "Litauen"},
    "卢森堡": {"en": "Luxembourg", "ja": "ルクセンブルク", "de": "Luxemburg"},
    "拉脱维亚": {"en": "Latvia", "ja": "ラトビア", "de": "Lettland"},
    "摩尔多瓦": {"en": "Moldova", "ja": "モルドバ", "de": "Moldau"},
    "马达加斯加": {"en": "Madagascar", "ja": "マダガスカル", "de": "Madagaskar"},
    "墨西哥": {"en": "Mexico", "ja": "メキシコ", "de": "Mexiko"},
    "马其顿": {"en": "North Macedonia", "ja": "北マケドニア", "de": "Nordmazedonien"},
    "马里": {"en": "Mali", "ja": "マリ", "de": "Mali"},
    "马耳他": {"en": "Malta", "ja": "マルタ", "de": "Malta"},
    "缅甸": {"en": "Myanmar", "ja": "ミャンマー", "de": "Myanmar"},
    "黑山": {"en": "Montenegro", "ja": "モンテネグロ", "de": "Montenegro"},
    "蒙古": {"en": "Mongolia", "ja": "モンゴル", "de": "Mongolei"},
    "N. Mariana Is.": {"en": "Northern Mariana Islands", "ja": "北マリアナ諸島", "de": "Nördliche Marianen"},
    "莫桑比克": {"en": "Mozambique", "ja": "モザンビーク", "de": "Mosambik"},
    "毛里塔尼亚": {"en": "Mauritania", "ja": "モーリタニア", "de": "Mauretanien"},
    "蒙塞拉特": {"en": "Montserrat", "ja": "モントセラト", "de": "Montserrat"},
    "毛里求斯": {"en": "Mauritius", "ja": "モーリシャス", "de": "Mauritius"},
    "马拉维": {"en": "Malawi", "ja": "マラウイ", "de": "Malawi"},
    "马来西亚": {"en": "Malaysia", "ja": "マレーシア", "de": "Malaysia"},
    "纳米比亚": {"en": "Namibia", "ja": "ナミビア", "de": "Namibia"},
    "新喀里多尼亚": {"en": "New Caledonia", "ja": "ニューカレドニア", "de": "Neukaledonien"},
    "尼日尔": {"en": "Niger", "ja": "ニジェール", "de": "Niger"},
    "尼日利亚": {"en": "Nigeria", "ja": "ナイジェリア", "de": "Nigeria"},
    "尼加拉瓜": {"en": "Nicaragua", "ja": "ニカラグア", "de": "Nicaragua"},
    "纽埃岛": {"en": "Niue", "ja": "ニウエ", "de": "Niue"},
    "荷兰": {"en": "Netherlands", "ja": "オランダ", "de": "Niederlande"},
    "挪威": {"en": "Norway", "ja": "ノルウェー", "de": "Norwegen"},
    "尼泊尔": {"en": "Nepal", "ja": "ネパール", "de": "Nepal"},
    "新西兰": {"en": "New Zealand", "ja": "ニュージーランド", "de": "Neuseeland"},
    "阿曼": {"en": "Oman", "ja": "オマーン", "de": "Oman"},
    "巴基斯坦": {"en": "Pakistan", "ja": "パキスタン", "de": "Pakistan"},
    "巴拿马": {"en": "Panama", "ja": "パナマ", "de": "Panama"},
    "秘鲁": {"en": "Peru", "ja": "ペルー", "de": "Peru"},
    "菲律宾": {"en": "Philippines", "ja": "フィリピン", "de": "Philippinen"},
    "帕劳": {"en": "Palau", "ja": "パラオ", "de": "Palau"},
    "巴布亚新几内亚": {"en": "Papua New Guinea", "ja": "パプアニューギニア", "de": "Papua-Neuguinea"},
    "波兰": {"en": "Poland", "ja": "ポーランド", "de": "Polen"},
    "波多黎各": {"en": "Puerto Rico", "ja": "プエルトリコ", "de": "Puerto Rico"},
    "朝鲜": {"en": "North Korea", "ja": "北朝鮮", "de": "Nordkorea"},
    "葡萄牙": {"en": "Portugal", "ja": "ポルトガル", "de": "Portugal"},
    "巴拉圭": {"en": "Paraguay", "ja": "パラグアイ", "de": "Paraguay"},
    "巴勒斯坦": {"en": "Palestine", "ja": "パレスチナ", "de": "Palästina"},
    "玻里尼西亚": {"en": "French Polynesia", "ja": "フランス領ポリネシア", "de": "Französisch-Polynesien"},
    "卡塔尔": {"en": "Qatar", "ja": "カタール", "de": "Katar"},
    "罗马尼亚": {"en": "Romania", "ja": "ルーマニア", "de": "Rumänien"},
    "俄罗斯": {"en": "Russia", "ja": "ロシア", "de": "Russland"},
    "卢旺达": {"en": "Rwanda", "ja": "ルワンダ", "de": "Ruanda"},
    "沙特阿拉伯": {"en": "Saudi Arabia", "ja": "サウジアラビア", "de": "Saudi-Arabien"},
    "苏丹": {"en": "Sudan", "ja": "スーダン", "de": "Sudan"},
    "南苏丹": {"en": "South Sudan", "ja": "南スーダン", "de": "Südsudan"},
    "塞内加尔": {"en": "Senegal", "ja": "セネガル", "de": "Senegal"},
    "新加坡": {"en": "Singapore", "ja": "シンガポール", "de": "Singapur"},
    "S. Geo. and S. Sandw. Is.": {"en": "South Georgia", "ja": "サウスジョージア", "de": "Südgeorgien"},
    "圣赫勒拿岛": {"en": "Saint Helena", "ja": "セントヘレナ", "de": "St. Helena"},
    "所罗门群岛": {"en": "Solomon Islands", "ja": "ソロモン諸島", "de": "Salomonen"},
    "塞拉利昂": {"en": "Sierra Leone", "ja": "シエラレオネ", "de": "Sierra Leone"},
    "萨尔瓦多": {"en": "El Salvador", "ja": "エルサルバドル", "de": "El Salvador"},
    "圣皮埃尔和密克隆": {"en": "Saint Pierre and Miquelon", "ja": "サンピエール島・ミクロン島", "de": "Saint-Pierre und Miquelon"},
    "圣多美和普林西比": {"en": "São Tomé and Príncipe", "ja": "サントメ・プリンシペ", "de": "São Tomé und Príncipe"},
    "苏里南": {"en": "Suriname", "ja": "スリナム", "de": "Suriname"},
    "斯洛伐克": {"en": "Slovakia", "ja": "スロバキア", "de": "Slowakei"},
    "斯洛文尼亚": {"en": "Slovenia", "ja": "スロベニア", "de": "Slowenien"},
    "瑞典": {"en": "Sweden", "ja": "スウェーデン", "de": "Schweden"},
    "斯威士兰": {"en": "Eswatini", "ja": "エスワティニ", "de": "Eswatini"},
    "塞舌尔共和国": {"en": "Seychelles", "ja": "セーシェル", "de": "Seychellen"},
    "叙利亚": {"en": "Syria", "ja": "シリア", "de": "Syrien"},
    "特克斯和凯科斯群岛": {"en": "Turks and Caicos Islands", "ja": "タークス・カイコス諸島", "de": "Turks- und Caicosinseln"},
    "乍得": {"en": "Chad", "ja": "チャド", "de": "Tschad"},
    "多哥": {"en": "Togo", "ja": "トーゴ", "de": "Togo"},
    "泰国": {"en": "Thailand", "ja": "タイ", "de": "Thailand"},
    "塔吉克斯坦": {"en": "Tajikistan", "ja": "タジキスタン", "de": "Tadschikistan"},
    "土库曼斯坦": {"en": "Turkmenistan", "ja": "トルクメニスタン", "de": "Turkmenistan"},
    "Timor-Leste": {"en": "Timor-Leste", "ja": "東ティモール", "de": "Osttimor"},
    "汤加": {"en": "Tonga", "ja": "トンガ", "de": "Tonga"},
    "特里尼达和多巴哥": {"en": "Trinidad and Tobago", "ja": "トリニダード・トバゴ", "de": "Trinidad und Tobago"},
    "突尼斯": {"en": "Tunisia", "ja": "チュニジア", "de": "Tunesien"},
    "土耳其": {"en": "Turkey", "ja": "トルコ", "de": "Türkei"},
    "坦桑尼亚": {"en": "Tanzania", "ja": "タンザニア", "de": "Tansania"},
    "乌干达": {"en": "Uganda", "ja": "ウガンダ", "de": "Uganda"},
    "乌克兰": {"en": "Ukraine", "ja": "ウクライナ", "de": "Ukraine"},
    "乌拉圭": {"en": "Uruguay", "ja": "ウルグアイ", "de": "Uruguay"},
    "美国": {"en": "United States", "ja": "アメリカ合衆国", "de": "Vereinigte Staaten"},
    "乌兹别克斯坦": {"en": "Uzbekistan", "ja": "ウズベキスタン", "de": "Usbekistan"},
    "圣文森特和格林纳丁斯": {"en": "Saint Vincent and the Grenadines", "ja": "セントビンセント・グレナディーン", "de": "St. Vincent und die Grenadinen"},
    "委内瑞拉": {"en": "Venezuela", "ja": "ベネズエラ", "de": "Venezuela"},
    "美属维尔京群岛": {"en": "U.S. Virgin Islands", "ja": "米領ヴァージン諸島", "de": "Amerikanische Jungferninseln"},
    "越南": {"en": "Vietnam", "ja": "ベトナム", "de": "Vietnam"},
    "瓦努阿图": {"en": "Vanuatu", "ja": "バヌアツ", "de": "Vanuatu"},
    "萨摩亚群岛": {"en": "Samoa", "ja": "サモア", "de": "Samoa"},
    "也门": {"en": "Yemen", "ja": "イエメン", "de": "Jemen"},
    "南非": {"en": "South Africa", "ja": "南アフリカ", "de": "Südafrika"},
    "赞比亚": {"en": "Zambia", "ja": "ザンビア", "de": "Sambia"},
    "津巴布韦": {"en": "Zimbabwe", "ja": "ジンバブエ", "de": "Simbabwe"},
}

CHINA_NAMES = {
    "北京市": {"en": "Beijing", "ja": "北京市", "de": "Peking"},
    "天津市": {"en": "Tianjin", "ja": "天津市", "de": "Tianjin"},
    "河北省": {"en": "Hebei", "ja": "河北省", "de": "Hebei"},
    "山西省": {"en": "Shanxi", "ja": "山西省", "de": "Shanxi"},
    "内蒙古自治区": {"en": "Inner Mongolia", "ja": "内モンゴル自治区", "de": "Innere Mongolei"},
    "辽宁省": {"en": "Liaoning", "ja": "遼寧省", "de": "Liaoning"},
    "吉林省": {"en": "Jilin", "ja": "吉林省", "de": "Jilin"},
    "黑龙江省": {"en": "Heilongjiang", "ja": "黒竜江省", "de": "Heilongjiang"},
    "上海市": {"en": "Shanghai", "ja": "上海市", "de": "Shanghai"},
    "江苏省": {"en": "Jiangsu", "ja": "江蘇省", "de": "Jiangsu"},
    "浙江省": {"en": "Zhejiang", "ja": "浙江省", "de": "Zhejiang"},
    "安徽省": {"en": "Anhui", "ja": "安徽省", "de": "Anhui"},
    "福建省": {"en": "Fujian", "ja": "福建省", "de": "Fujian"},
    "江西省": {"en": "Jiangxi", "ja": "江西省", "de": "Jiangxi"},
    "山东省": {"en": "Shandong", "ja": "山東省", "de": "Shandong"},
    "河南省": {"en": "Henan", "ja": "河南省", "de": "Henan"},
    "湖北省": {"en": "Hubei", "ja": "湖北省", "de": "Hubei"},
    "湖南省": {"en": "Hunan", "ja": "湖南省", "de": "Hunan"},
    "广东省": {"en": "Guangdong", "ja": "広東省", "de": "Guangdong"},
    "广西壮族自治区": {"en": "Guangxi", "ja": "広西チワン族自治区", "de": "Guangxi"},
    "海南省": {"en": "Hainan", "ja": "海南省", "de": "Hainan"},
    "重庆市": {"en": "Chongqing", "ja": "重慶市", "de": "Chongqing"},
    "四川省": {"en": "Sichuan", "ja": "四川省", "de": "Sichuan"},
    "贵州省": {"en": "Guizhou", "ja": "貴州省", "de": "Guizhou"},
    "云南省": {"en": "Yunnan", "ja": "雲南省", "de": "Yunnan"},
    "西藏自治区": {"en": "Tibet", "ja": "チベット自治区", "de": "Tibet"},
    "陕西省": {"en": "Shaanxi", "ja": "陝西省", "de": "Shaanxi"},
    "甘肃省": {"en": "Gansu", "ja": "甘粛省", "de": "Gansu"},
    "青海省": {"en": "Qinghai", "ja": "青海省", "de": "Qinghai"},
    "宁夏回族自治区": {"en": "Ningxia", "ja": "寧夏回族自治区", "de": "Ningxia"},
    "新疆维吾尔自治区": {"en": "Xinjiang", "ja": "新疆ウイグル自治区", "de": "Xinjiang"},
    "台湾省": {"en": "Taiwan", "ja": "台湾", "de": "Taiwan"},
    "香港特别行政区": {"en": "Hong Kong", "ja": "香港", "de": "Hongkong"},
    "澳门特别行政区": {"en": "Macau", "ja": "マカオ", "de": "Macau"},
}

JAPAN_NAMES = {
    "北海道": {"en": "Hokkaido", "ja": "北海道", "de": "Hokkaidō"},
    "青森县": {"en": "Aomori", "ja": "青森県", "de": "Aomori"},
    "岩手县": {"en": "Iwate", "ja": "岩手県", "de": "Iwate"},
    "宫城县": {"en": "Miyagi", "ja": "宮城県", "de": "Miyagi"},
    "秋田县": {"en": "Akita", "ja": "秋田県", "de": "Akita"},
    "山形县": {"en": "Yamagata", "ja": "山形県", "de": "Yamagata"},
    "福岛县": {"en": "Fukushima", "ja": "福島県", "de": "Fukushima"},
    "茨城县": {"en": "Ibaraki", "ja": "茨城県", "de": "Ibaraki"},
    "栃木县": {"en": "Tochigi", "ja": "栃木県", "de": "Tochigi"},
    "群马县": {"en": "Gunma", "ja": "群馬県", "de": "Gunma"},
    "埼玉县": {"en": "Saitama", "ja": "埼玉県", "de": "Saitama"},
    "千叶县": {"en": "Chiba", "ja": "千葉県", "de": "Chiba"},
    "东京": {"en": "Tokyo", "ja": "東京都", "de": "Tokio"},
    "神奈川县": {"en": "Kanagawa", "ja": "神奈川県", "de": "Kanagawa"},
    "新潟县": {"en": "Niigata", "ja": "新潟県", "de": "Niigata"},
    "富山县": {"en": "Toyama", "ja": "富山県", "de": "Toyama"},
    "石川县": {"en": "Ishikawa", "ja": "石川県", "de": "Ishikawa"},
    "福井县": {"en": "Fukui", "ja": "福井県", "de": "Fukui"},
    "山梨县": {"en": "Yamanashi", "ja": "山梨県", "de": "Yamanashi"},
    "长野县": {"en": "Nagano", "ja": "長野県", "de": "Nagano"},
    "岐阜县": {"en": "Gifu", "ja": "岐阜県", "de": "Gifu"},
    "静冈县": {"en": "Shizuoka", "ja": "静岡県", "de": "Shizuoka"},
    "爱知县": {"en": "Aichi", "ja": "愛知県", "de": "Aichi"},
    "三重县": {"en": "Mie", "ja": "三重県", "de": "Mie"},
    "滋贺县": {"en": "Shiga", "ja": "滋賀県", "de": "Shiga"},
    "京都府": {"en": "Kyoto", "ja": "京都府", "de": "Kyōto"},
    "大阪府": {"en": "Osaka", "ja": "大阪府", "de": "Ōsaka"},
    "兵库县": {"en": "Hyogo", "ja": "兵庫県", "de": "Hyōgo"},
    "奈良县": {"en": "Nara", "ja": "奈良県", "de": "Nara"},
    "和歌山县": {"en": "Wakayama", "ja": "和歌山県", "de": "Wakayama"},
    "鳥取县": {"en": "Tottori", "ja": "鳥取県", "de": "Tottori"},
    "鸟取县": {"en": "Tottori", "ja": "鳥取県", "de": "Tottori"},
    "岛根县": {"en": "Shimane", "ja": "島根県", "de": "Shimane"},
    "冈山县": {"en": "Okayama", "ja": "岡山県", "de": "Okayama"},
    "广岛县": {"en": "Hiroshima", "ja": "広島県", "de": "Hiroshima"},
    "山口县": {"en": "Yamaguchi", "ja": "山口県", "de": "Yamaguchi"},
    "德岛县": {"en": "Tokushima", "ja": "徳島県", "de": "Tokushima"},
    "香川县": {"en": "Kagawa", "ja": "香川県", "de": "Kagawa"},
    "爱媛县": {"en": "Ehime", "ja": "愛媛県", "de": "Ehime"},
    "高知县": {"en": "Kochi", "ja": "高知県", "de": "Kōchi"},
    "福冈县": {"en": "Fukuoka", "ja": "福岡県", "de": "Fukuoka"},
    "佐贺县": {"en": "Saga", "ja": "佐賀県", "de": "Saga"},
    "长崎县": {"en": "Nagasaki", "ja": "長崎県", "de": "Nagasaki"},
    "熊本县": {"en": "Kumamoto", "ja": "熊本県", "de": "Kumamoto"},
    "大分县": {"en": "Oita", "ja": "大分県", "de": "Ōita"},
    "宫崎县": {"en": "Miyazaki", "ja": "宮崎県", "de": "Miyazaki"},
    "鹿儿岛县": {"en": "Kagoshima", "ja": "鹿児島県", "de": "Kagoshima"},
    "冲绳县": {"en": "Okinawa", "ja": "沖縄県", "de": "Okinawa"},
}

GERMANY_NAMES = {
    "Baden-Württemberg": {"zh": "巴登-符腾堡", "en": "Baden-Württemberg", "ja": "バーデン＝ヴュルテンベルク", "de": "Baden-Württemberg"},
    "Bayern": {"zh": "巴伐利亚", "en": "Bavaria", "ja": "バイエルン", "de": "Bayern"},
    "Berlin": {"zh": "柏林", "en": "Berlin", "ja": "ベルリン", "de": "Berlin"},
    "Brandenburg": {"zh": "勃兰登堡", "en": "Brandenburg", "ja": "ブランデンブルク", "de": "Brandenburg"},
    "Bremen": {"zh": "不来梅", "en": "Bremen", "ja": "ブレーメン", "de": "Bremen"},
    "Hamburg": {"zh": "汉堡", "en": "Hamburg", "ja": "ハンブルク", "de": "Hamburg"},
    "Hessen": {"zh": "黑森", "en": "Hesse", "ja": "ヘッセン", "de": "Hessen"},
    "Mecklenburg-Vorpommern": {"zh": "梅克伦堡-前波莫瑞", "en": "Mecklenburg-Vorpommern", "ja": "メクレンブルク＝フォアポンメルン", "de": "Mecklenburg-Vorpommern"},
    "Niedersachsen": {"zh": "下萨克森", "en": "Lower Saxony", "ja": "ニーダーザクセン", "de": "Niedersachsen"},
    "Nordrhein-Westfalen": {"zh": "北莱茵-威斯特法伦", "en": "North Rhine-Westphalia", "ja": "ノルトライン＝ヴェストファーレン", "de": "Nordrhein-Westfalen"},
    "Rheinland-Pfalz": {"zh": "莱茵兰-普法尔茨", "en": "Rhineland-Palatinate", "ja": "ラインラント＝プファルツ", "de": "Rheinland-Pfalz"},
    "Saarland": {"zh": "萨尔", "en": "Saarland", "ja": "ザールラント", "de": "Saarland"},
    "Sachsen-Anhalt": {"zh": "萨克森-安哈尔特", "en": "Saxony-Anhalt", "ja": "ザクセン＝アンハルト", "de": "Sachsen-Anhalt"},
    "Sachsen": {"zh": "萨克森", "en": "Saxony", "ja": "ザクセン", "de": "Sachsen"},
    "Schleswig-Holstein": {"zh": "石勒苏益格-荷尔斯泰因", "en": "Schleswig-Holstein", "ja": "シュレースヴィヒ＝ホルシュタイン", "de": "Schleswig-Holstein"},
    "Thüringen": {"zh": "图林根", "en": "Thuringia", "ja": "テューリンゲン", "de": "Thüringen"},
}

# fmt: on


def add_translations(filepath: str, translations: dict, has_zh_key: bool = False) -> None:
    """给 GeoJSON 文件添加多语言字段。"""
    with open(filepath, encoding="utf-8") as f:
        data = json.load(f)

    missing = []
    for feat in data["features"]:
        name = feat["properties"].get("name", "")
        if not name:
            continue
        trans = translations.get(name)
        if trans:
            if has_zh_key:
                feat["properties"]["name"] = trans.get("zh", name)
                feat["properties"]["name_en"] = trans.get("en", name)
            else:
                feat["properties"]["name_en"] = trans.get("en", name)
            feat["properties"]["name_ja"] = trans.get("ja", name)
            feat["properties"]["name_de"] = trans.get("de", name)
        else:
            missing.append(name)

    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, separators=(",", ":"))

    total = len(data["features"])
    translated = total - len(missing)
    print(f"  {os.path.basename(filepath)}: {translated}/{total} translated")
    if missing:
        print(f"    missing: {missing}")


def main() -> None:
    """主入口。"""
    print("Adding multi-language names to GeoJSON files...")

    add_translations(os.path.join(GEO_DIR, "world.json"), WORLD_NAMES)
    add_translations(os.path.join(GEO_DIR, "china.json"), CHINA_NAMES)
    add_translations(os.path.join(GEO_DIR, "japan.json"), JAPAN_NAMES)
    add_translations(os.path.join(GEO_DIR, "germany.json"), GERMANY_NAMES, has_zh_key=True)
    add_translations(
        os.path.join(GEO_DIR, "singapore.json"),
        {"新加坡": {"en": "Singapore", "ja": "シンガポール", "de": "Singapur"}},
    )

    print("Done!")


if __name__ == "__main__":
    main()
